name: Close Issues

on:
  issues:
    types: [closed]

env:
  GH_TOKEN: ${{ secrets.TOKEN }}

jobs:
  remove-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Remove `ready-to-test` Label
        run: |
            # get closed issue with label "ready-to-test"
            issues="$(gh issue list -s closed -l "#status: ready-to-test :heavy_check_mark:" --json id --jq '.[] | .id')"

            # process issues
            for issueId in $issues; do
              gh api graphql -F issueId='$issueId' -F labelId='LA_kwDODbcoCM8AAAABfA96zA' -f query='
            			mutation UpdateIssue_RemoveLabel($issueId: ID!, $labelId: ID!) {
            				removeLabelsFromLabelable(input: {
            					labelIds: [ $labelId ],
            					labelableId: $issueId
            				}) {
            					clientMutationId,
            					labelable { labels (first: 100) { nodes { name }} }
            				}
            			}'
            done
