name: Github publish

on:
  push

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: 12
            registry-url: "https://npm.pkg.github.com"
            scope: "@zefau"
      - run: npm install
      - run: echo "registry=https://npm.pkg.github.com/@zefau" >> .npmrc
      - run: npm publish
        env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
